#!/bin/sh

set -e

CDPATH="" cd -- "$(dirname -- "$(dirname -- "$0")")"

mkdir -p bin

BINDOWN_VERSION="4.5.0"

if ! [ -f bin/bindown ]; then
  set +e
  VERSION_OUTPUT="$(bin/bindown version 2> /dev/null)"
  set -e
  if ! echo "$VERSION_OUTPUT" || grep -q "$BINDOWN_VERSION"; then
    sh -c "$(
      curl -sfL https://github.com/WillAbides/bindown/releases/download/"v$BINDOWN_VERSION"/bootstrap-bindown.sh
    )"
  fi
fi

exec bin/bindown "$@"
