#!/bin/sh
#/ script/bootstrap installs dependencies for testing and development.

set -e

CDPATH="" cd -- "$(dirname -- "$0")/.."

mkdir -p ./external

script/bindown install --output ./external/shunit2 shunit2
