#!/bin/sh
#/ script/lint runs linters on the project.

set -e

CDPATH="" cd -- "$(dirname -- "$0")/.."

script/bootstrap
script/bindown -q install shellcheck
script/bindown -q install zizmor

bin/shellcheck -e SC1071 -x ./script/* ./src/* ./.github/workflows/script/*
bin/zizmor --no-progress .github/workflows/
