#!/bin/sh

set -e

CDPATH="" cd -- "$(dirname -- "$(dirname -- "$0")")"

if [ "$1" = "-long" ]; then
  for f in ./src/*_test_long.*; do
    "$f"
  done
  exit
fi

for f in ./src/*_test.*; do
  "$f"
done
