#!/bin/bash

set -e
[ -n "$DEBUG" ] && set -x

CDPATH="" cd -- "$(dirname -- "$(dirname -- "$0")")"

. src/lib

debug_out starting head-go-version

version="$1"

mock_head_go_version="${mock_head_go_version:-""}"
if [ -n "$mock_head_go_version" ]; then
  available_head_versions="${available_head_versions:-""}"
  for ver in $available_head_versions; do
    if [ "$ver" = "$version" ]; then
      exit 0
    fi
  done
  exit 1
fi

. src/lib

check_url="$(download_go_url "$version")"
curl -IL --fail -s "$check_url" >/dev/null
