#!/bin/bash

# required args:
# $1 - constraint (^1.2.3)
# $2 - tool cache (${{runner.tool_cache}}/go)
#
# env vars:
# IGNORE_LOCAL_GO

set -e
[ -n "$DEBUG" ] && set -x

CDPATH="" cd -- "$(dirname -- "$(dirname -- "$0")")"

. src/lib

debug_out starting resolve-go-version

GO_VERSION_CONSTRAINT="$1"
#GO_TOOL_CACHE="$2"

if is_precise_version "$GO_VERSION_CONSTRAINT"; then
  echo "$GO_VERSION_CONSTRAINT"
  exit
fi

# special case for gotip
if [ "$GO_VERSION_CONSTRAINT" = "gotip" ] || [ "$GO_VERSION_CONSTRAINT" = "tip" ]; then
  echo "tip"
  exit
fi

#if [ -z "$IGNORE_LOCAL_GO" ]; then
#  lv="$(select_local_version "$GO_VERSION_CONSTRAINT" "$GO_TOOL_CACHE")"
#  if [ -n "$lv" ]; then
#    echo "$lv" && exit
#  fi
#fi

if [ -z "$dl_json" ]; then
  dl_json="$(curl --retry 4 -s --fail 'https://golang.org/dl/?mode=json&include=all')"
fi

select_remote_version "$GO_VERSION_CONSTRAINT" "$dl_json"
