#!/bin/bash

set -e
[ -n "$DEBUG" ] && set -x

CDPATH="" cd -- "$(dirname -- "$0")/.."

goos() {
  case "$RUNNER_OS" in
    macOS)
      echo "darwin"
      ;;
    Linux)
      echo "linux"
      ;;
    Windows)
      echo "windows"
      ;;
    *)
      uname -s | tr '[:upper:]' '[:lower:]'
      ;;
  esac
}

target_version="0.3.0"
bin_path="./bin/semver-select"
[ "$(goos)" = "windows" ] && bin_path+=".exe"

skip_download() {
  [ -f "$bin_path" ] || return
  chmod +x "$bin_path"
  got_ver="$("$bin_path" -v)"
  [ "$got_ver" == "$target_version" ]
}

download() {
  skip_download && return
  mkdir -p "$(dirname "$bin_path")"
  url="https://github.com/WillAbides/semver-select/releases/download/v"
  url+="$target_version/semver-select_${target_version}_$(goos)_amd64"
  [ "$(goos)" = "windows" ] && url+=".exe"
  curl -s --fail -o "$bin_path" --retry 4 -L "$url"
  chmod +x "$bin_path"
}

download

exec "$bin_path" "$@"
