name: release-check

on:
  pull_request:
    types: [opened, reopened, synchronize, labeled, unlabeled]

permissions: {}

jobs:
  releasable:
    name: releasable
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      pull-requests: read
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
      - name: release-train (check-pr)
        uses: WillAbides/release-train@a234a745371bf2fef3d64d74e1e9381aa9e6d4f8 # v3.8.6
        with:
          release-refs: main
